### ISSUE TITLE
Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class io.swagger.converter.ModelConverters

### ISSUE THREAD

**Issue by 58a36f** [swagger-api/swagger-play#126]
Hello,

 I already thought that this should be solved in 1.5.3 according to issues, but I have 1.5.3

` "io.swagger" %% "swagger-play2" % "1.5.3"`

and I am still getting following error:

`CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class io.swagger.converter.ModelConverters
  at play.modules.swagger.SwaggerPluginImpl.<init>(SwaggerPlugin.scala:35)
  while locating play.modules.swagger.SwaggerPluginImpl
  at play.modules.swagger.SwaggerModule.bindings(SwaggerModule.scala:11):
Binding(interface play.modules.swagger.SwaggerPlugin to ConstructionTarget(class play.modules.swagger.SwaggerPluginImpl) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating play.modules.swagger.SwaggerPlugin

1 error`

**Comment by fehguy** [comment]
Please re-test with 1.5.4-SNAPSHOT which is in sonatype.

**Comment by sarat1991** [comment]
Hi fehguy, 
  From where can I download 1.5.4-SNAPSHOT dependency. I couldn't find it in mvn repository.

**Comment by pocketwalker** [comment]
I'm getting this error in 1.6.0!
