### ISSUE TITLE
Update to Play 2.7

### ISSUE THREAD

**Issue by notflorian** [swagger-api/swagger-play#187]
Hello,

[Play 2.7 is here](https://blog.playframework.com/play-2-7-0-is-here/).

Could you please update your library to be compatible with this version?

Currently in [my project](https://github.com/KelkooGroup/theGardener/tree/feature/update-play) I get[ the following exception](https://travis-ci.org/KelkooGroup/theGardener/builds/487516366) `java.lang.NoClassDefFoundError: Could not initialize class io.swagger.converter.ModelConverters`

Many thanks

**Comment by henricook** [comment]
We currently see:

```
	at com.iheart.playSwagger.Domain$CustomTypeMapping$.<init>(Domain.scala:59)
	at com.iheart.playSwagger.Domain$CustomTypeMapping$.<clinit>(Domain.scala)
	at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings$lzycompute(SwaggerSpecGenerator.scala:260)
	at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings(SwaggerSpecGenerator.scala:259)
	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$4(SwaggerSpecGenerator.scala:370)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$2(SwaggerSpecGenerator.scala:368)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at com.iheart.playSwagger.SwaggerSpecGenerator.endPointSpec(SwaggerSpecGenerator.scala:367)
	at com.iheart.playSwagger.SwaggerSpecGenerator.endPointEntry(SwaggerSpecGenerator.scala:333)
	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$paths$1(SwaggerSpecGenerator.scala:309)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at com.iheart.playSwagger.SwaggerSpecGenerator.paths(SwaggerSpecGenerator.scala:309)
	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutes$1(SwaggerSpecGenerator.scala:124)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:121)
	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:106)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:105)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:50)
```

**Comment by sitwaheed9** [comment]
please update the swagger for play 2.7

**Comment by thomaska** [comment]
I think the reason for this is that play 2.7 uses a later version of `com.fasterxml.jackson.core:jackson-databind` (namely 2.9.8) with which swagger 1.6.x is not compatible with (it uses 2.8.6).
Overriding the dependency in sbt worked for me (although I haven't tested it extensively).
This means I added this in my `build.sbt` file
```
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.6"
```
This as a workaround, until swagger gets updated, which would be the proper solution.

**Comment by youqian** [comment]
Will you guys release a version for playframework 2.7 soon?

For now I added jackson-module-scala-2.9.8 together with swagger-play deps.
val swagger = Seq(
  "io.swagger"                   %% "swagger-play2"        % "1.6.0",
  "io.swagger"                   % "swagger-core"          % "1.5.22",
  "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.9.8",
  "org.webjars"                  % "swagger-ui"            % "3.13.0"
)
