### ISSUE TITLE
Custom ApplicationLoader

### ISSUE THREAD

**Issue by YannMoisan** [swagger-api/swagger-play#51]
Is it possible to use swagger-play with a custom `ApplicationLoader`.
I need to get a reference to `ApiHelpController` to instantiate the `Routes` object manually.

I've tried :

```
override lazy val router = new Routes(httpErrorHandler, applicationController, assets, new ApiHelpController())
```

but I've encountered this error .

```
Caused by: java.lang.NullPointerException: null
    at play.modules.swagger.ApiListingCache$$anonfun$listing$1.apply(ApiListingCache.scala:15) ~[swagger-play2_2.11-1.5.0.jar:1.5.0]
    at play.modules.swagger.ApiListingCache$$anonfun$listing$1.apply(ApiListingCache.scala:11) ~[swagger-play2_2.11-1.5.0.jar:1.5.0]
    at scala.Option.orElse(Option.scala:289) ~[scala-library-2.11.7.jar:na]
    at play.modules.swagger.ApiListingCache$.listing(ApiListingCache.scala:11) ~[swagger-play2_2.11-1.5.0.jar:1.5.0]
    at controllers.SwaggerBaseApiController.getResourceListing(ApiHelpController.scala:128) ~[swagger-play2_2.11-1.5.0.jar:2.4.6]
    at controllers.ApiHelpController$$anonfun$getResources$1.apply(ApiHelpController.scala:74) ~[swagger-play2_2.11-1.5.0.jar:2.4.6]
    at controllers.ApiHelpController$$anonfun$getResources$1.apply(ApiHelpController.scala:71) ~[swagger-play2_2.11-1.5.0.jar:2.4.6]
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.6.jar:2.4.6]
    at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.6.jar:2.4.6]
```

**Comment by frantuma** [comment]
helper added in #53
