### ISSUE TITLE
Initialisation problem using swagger-play2 1.5.1

### ISSUE THREAD

**Issue by UlTriX** [swagger-api/swagger-play#54]
I get the following error during the initialisation of Swagger when the application is run in jar form

```
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at play.modules.swagger.SwaggerPluginImpl.play$modules$swagger$SwaggerPluginImpl$$parseRoutesHelper$1(SwaggerPlugin.scala:119)
```

It seems to me getResource() is not the best approach when in jar form 
I think the solution is using getResourceAsStream

**Comment by UlTriX** [comment]
I was using PlayKeys.externalizeResources once the error
