### ISSUE TITLE
application.conf should not be in swagger-play2

### ISSUE THREAD

**Issue by matiwinnetou** [swagger-api/swagger-play#55]
Normally things work but when one uses https://github.com/sbt/sbt-assembly there is an issue while merging files. If I am not mistaken one should not include an empty application.conf in plugins.

Perhaps as a workaround I will merge files (resolution strategy) but nonetheless it is not recommended to have empty application.conf in play plugin's directory.

**Comment by matiwinnetou** [comment]
Ok, that didn't help much, there are other problems when using sbt-assembly:

line 119 in SwaggerPlugin does not work, it cannot access routes file from within a jar file.

Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init>(File.java:418)
    at play.modules.swagger.SwaggerPluginImpl.play$modules$swagger$SwaggerPluginImpl$$parseRoutesHelper$1(SwaggerPlugin.scala:119)
    at play.modules.swagger.SwaggerPluginImpl.parseRoutes(SwaggerPlugin.scala:133)
    at play.modules.swagger.SwaggerPluginImpl.<init>(SwaggerPlugin.scala:104)
    at play.modules.swagger.SwaggerPluginImpl$$FastClassByGuice$$de7219b8.newInstance(<generated>)

**Comment by matiwinnetou** [comment]
Fix to be reviewed here: https://github.com/swagger-api/swagger-play/pull/56
