### ISSUE TITLE
IllegalArgumentException in 2.4 using stage task

### ISSUE THREAD

**Issue by lanceo7** [swagger-api/swagger-play#58]
I’m having trouble upgrading with swagger Play Java from 2.3 to 2.4.  It worked fine for me with 2.3.

The issue I’m having is accessing the routes file.  In SwaggerPlugin.scala line 119 there is this line, where the routes file is parsed.

`val parsedRoutes = RoutesFileParser.parse(new File(app.classloader.getResource(routesFile).toURI))
`

This is running fine for me in the IDE (IntelliJ) or via activator run.  However, after running activator compile stage, and then executing it via the generated launcher script in target/universal/stage/bin  it fails.  The error I’m getting is thrown from the Guice at startup, but the nested exception is this.  Line numbers are slightly off due to my adding some println statements.

```
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init>(File.java:418)
    at play.modules.swagger.SwaggerPluginImpl.play$modules$swagger$SwaggerPluginImpl$$parseRoutesHelper$1(SwaggerPlugin.scala:122)
    at play.modules.swagger.SwaggerPluginImpl.parseRoutes(SwaggerPlugin.scala:137)
    at play.modules.swagger.SwaggerPluginImpl.<init>(SwaggerPlugin.scala:104)
    at play.modules.swagger.SwaggerPluginImpl$$FastClassByGuice$$de7219b8.newInstance(<generated>)
    at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)

```

I’ve hacked into SwaggerPlugin and added a print statement.  The URL begin passed to the File constructor is
`jar:file:/Users/lanceo/heroku/dev/target/universal/stage/lib/server.server-1.0-SNAPSHOT.jar!/routes
`
That looks to me like a valid jar: protocol, but this SO indicates that is not allowed with the File contractor.  http://stackoverflow.com/questions/10144210/java-jar-file-use-resource-errors-uri-is-not-hierarchical

Running the app with the stage command is a supported deployment method (https://www.playframework.com/documentation/2.4.x/Production).  It is how Heroku runs a Play app.  Any ideas on work arounds?

**Comment by frantuma** [comment]
fixed in #64 and version 1.5.2
