### ISSUE TITLE
Submodule Route throw java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by npeters** [swagger-api/swagger-play#63]
When my route file include a submodule, my playframework throw a exception. 

Route file
`
~> /admin admin.Routes
`
then 
`
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init>(File.java:418) ~[na:1.8.0_51]
    at play.modules.swagger.SwaggerPluginImpl.play$modules$swagger$SwaggerPluginImpl$$parseRoutesHelper$1(SwaggerPlugin.scala:119) ~[swagger-play2_2.11.jar:1.5.1]
    at play.modules.swagger.SwaggerPluginImpl$$anonfun$1.applyOrElse(SwaggerPlugin.scala:127) ~[swagger-play2_2.11.jar:1.5.1]
    at play.modules.swagger.SwaggerPluginImpl$$anonfun$1.applyOrElse(SwaggerPlugin.scala:120) ~[swagger-play2_2.11.jar:1.5.1]
    at scala.collection.immutable.List.collect(List.scala:303) ~[scala-library-2.11.7.jar:na]
    at play.modules.swagger.SwaggerPluginImpl.play$modules$swagger$SwaggerPluginImpl$$parseRoutesHelper$1(SwaggerPlugin.scala:120) ~[swagger-play2_2.11.jar:1.5.1]
`

**Comment by cosmolev** [comment]
I have the same issue. It will be fixed by this pull request: https://github.com/swagger-api/swagger-play/pull/56 .
